// pages/_app.tsx
import "bootstrap/dist/css/bootstrap.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "../styles/base.css";
import "../styles/main.css";

import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { AppProps } from "next/app";

function MainApp({ Component, pageProps, router }: AppProps) {
  return (
    <div id="wrapper" className="margLTop margLBottom">
      <Head>
        <title>Elahe Dastan</title>
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌰</text></svg>"
        />
      </Head>
      <div className="container">
        <div className="row">
          <div className="col-md-3 left-content">
            <header id="header">
              <div className="main-header">
                <figure className="img-profile">
                  <Image
                    src="/me-1.jpg"
                    width={1024}
                    height={1024}
                    alt="Elahe Dastan"
                  />
                  <figcaption className="name-profile">
                    <span>ELAHE DASTAN</span>
                  </figcaption>
                </figure>
                <nav id="main-nav" className="main-nav clearfix tabbed">
                  <ul>
                    <li className="nav-item">
                      <Link
                        href="/"
                        className={
                          "nav-link " +
                          (router.pathname === "/" ? "active" : "")
                        }
                      >
                        <i className="fas fa-user"></i>About Me
                      </Link>
                    </li>
                    <li className="nav-item">
                      <Link
                        href="/education"
                        className={
                          "nav-link " +
                          (router.pathname === "/education" ? "active" : "")
                        }
                      >
                        <i className="fas fa-graduation-cap"></i>Education
                      </Link>
                    </li>
                    <li className="nav-item">
                      <Link
                        href="/experience"
                        className={
                          "nav-link " +
                          (router.pathname === "/experience" ? "active" : "")
                        }
                      >
                        <i className="fas fa-briefcase"></i>Work
                      </Link>
                    </li>
                    <li className="nav-item">
                      <Link
                        href="/contact"
                        className={
                          "nav-link " +
                          (router.pathname === "/contact" ? "active" : "")
                        }
                      >
                        <i className="fas fa-pen"></i>Contact
                      </Link>
                    </li>
                  </ul>
                </nav>
              </div>
              <div className="bottom-header bgWhite ofsTSmall ofsBSmall tCenter">
                <ul className="social">
                  <li className="anim">
                    <a
                      href="https://github.com/elahe-dastan"
                      target="_blank"
                      rel="noreferrer"
                    >
                      <i className="fab fa-github"></i>
                    </a>
                  </li>
                  <li className="anim">
                    <a
                      href="https://instagram.com/elahe.dstn"
                      target="_blank"
                      rel="noreferrer"
                    >
                      <i className="fab fa-instagram"></i>
                    </a>
                  </li>
                </ul>
                <p></p>
              </div>
            </header>
          </div>
          <div className="col-md-9 right-content">
            <Component {...pageProps} />
          </div>
        </div>
      </div>
    </div>
  );
}

export default MainApp;

// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
export class AppComponent {
  title = 'raha';
}

<!--Wrapper-->
<div id="wrapper" class="margLTop margLBottom">
  <!--Container-->
  <div class="container">
    <div class="row">
      <!--Left content-->
      <div class="col-md-3 left-content">
        <!--Header-->
        <header id="header">
          <!--Main header-->
          <div class="main-header">
            <!--Profile image-->
            <figure class="img-profile">
              <img src="assets/img/profile.jpg" alt="Elahe Dastan">
              <figcaption class="name-profile"><span>ELAHE DASTAN</span></figcaption>
            </figure>
            <!--End profile image-->
            <!--Main navigation-->
            <nav id="main-nav" class="main-nav clearfix tabbed">
              <ul>
                <li class="nav-item">
                  <a routerLink="/about" routerLinkActive="active" class="nav-link"><i class="fas fa-user"></i>About Me</a>
                </li>
                <li class="nav-item">
                  <a routerLink="/education" routerLinkActive="active" class="nav-link"><i class="fas fa-graduation-cap"></i>Education</a>
                </li>
                <li class="nav-item">
                  <a routerLink="/experience" routerLinkActive="active" class="nav-link"><i class="fas fa-briefcase"></i>Work</a>
                </li>
                <li class="nav-item">
                  <a routerLink="/contact" routerLinkActive="active" class="nav-link"><i class="fas fa-pen"></i>Contact</a>
                </li>
              </ul>
            </nav>
            <!--End main navigation-->
          </div>
          <!--End main header-->
          <div class="bottom-header bgWhite ofsTSmall ofsBSmall tCenter">
            <ul class="social">
              <li class="anim">
                <a href="https://github.com/elahe-dastan" target="_blank"><i class="fab fa-github"></i></a>
              </li>
              <li class="anim">
                <a href="https://instagram.com/elahe.dstn" target="_blank"><i class="fab fa-instagram"></i></a>
              </li>
            </ul>
            <p></p>
          </div>
        </header>
        <!--End  header-->
      </div>
      <!--End left content-->
      <!--Right content-->
      <div class="col-md-9 right-content">
        <router-outlet></router-outlet>
      </div>
      <!--End right content-->
    </div>
    <!--End row-->
  </div>
  <!--End container-->
</div>
<!--End wrapper-->
